# Generated by Django 5.2.3 on 2025-07-20 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product_total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
