# Generated by Django 5.2.3 on 2025-06-28 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('stock', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('warranty', models.CharField(max_length=100, null=True)),
                ('return_policy', models.CharField(blank=True, default='10 Days return', max_length=100, null=True)),
                ('delivery_info', models.CharField(blank=True, default='Free Delivery', max_length=100, null=True)),
                ('created_at', models.DateField(auto_now=True)),
                ('sale', models.BooleanField(default=False)),
                ('trending', models.BooleanField(default=False)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
        ),
        migrations.CreateModel(
            name='Airconditioner',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('tonnage', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('energy_rating', models.CharField(max_length=100)),
                ('cooling_capacity', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Babycare',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('age_group', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('hypoallergic', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('author', models.CharField(max_length=100)),
                ('publiser', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('pages', models.IntegerField()),
                ('publication_date', models.DateField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('camera_type', models.CharField(max_length=100)),
                ('megapixels', models.CharField(max_length=100)),
                ('optical_zoom', models.CharField(max_length=100)),
                ('sensor_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('size', models.CharField(max_length=10)),
                ('fabric', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Earbuds',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('battery_life', models.CharField(max_length=100)),
                ('bluetooth_version', models.CharField(max_length=50)),
                ('has_anc', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Footwear',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('size', models.CharField(max_length=10)),
                ('material', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('material', models.CharField(max_length=10)),
                ('dimensions', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('weight', models.CharField(max_length=100)),
                ('expiry_date', models.CharField(max_length=100)),
                ('pack_type', models.CharField(max_length=100)),
                ('organic', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Kitchenappliance',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('appliance_type', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('graphic_card', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Lighting',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('light_type', models.CharField(max_length=10)),
                ('wattage', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('is_rechareable', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('ram', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('battery', models.CharField(max_length=100)),
                ('mobile_camera', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('screen_size', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Refrigerator',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('capacity', models.CharField(max_length=100)),
                ('door_type', models.CharField(max_length=100)),
                ('energy_rating', models.CharField(max_length=100)),
                ('defrost_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Smartwatch',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('screen_size', models.CharField(max_length=100)),
                ('battery_life', models.CharField(max_length=100)),
                ('features', models.TextField()),
                ('water_resistant', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('screen_size', models.CharField(max_length=100)),
                ('resolution', models.CharField(max_length=100)),
                ('smart_tv', models.BooleanField(default=False)),
                ('hdmi_ports', models.IntegerField()),
                ('usb_ports', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.CreateModel(
            name='WashingMachine',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Products.product')),
                ('type', models.CharField(max_length=100)),
                ('capacity', models.CharField(max_length=100)),
                ('function_type', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('Products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.category_product'),
        ),
    ]
